create table category_type (TYPE_ID varchar(20) not null, CATEGORY_ID varchar(20) not null, primary key (CATEGORY_ID, TYPE_ID));
create table address (ADDRESS_ID varchar(20) not null, NAME varchar(40), COUNTRY varchar(30), BLDG_NUM varchar(10), STREET_DIRECTION varchar(20), ADDRESS1 varchar(45), ADDRESS2 varchar(45), ADDRESS3 varchar(45), ADDRESS4 varchar(45), ADDRESS5 varchar(45), ADDRESS6 varchar(45), ADDRESS7 varchar(45), CITY varchar(30), STATE varchar(15), POSTAL_CD varchar(10), IS_DEFAULT integer, DESCRIPTION varchar(100), ACTIVE integer, PARENT_ID varchar(20) not null, PARENT_TYPE varchar(30) not null, primary key (ADDRESS_ID));
create table category (CATEGORY_ID varchar(20) not null, PARENT_ID varchar(20), CATEGORY_NAME varchar(40), CATEGORY_DESC varchar(80), CREATE_DATE timestamp, CREATED_BY varchar(20), SHOW_LIST integer, DISPLAY_ORDER integer, primary key (CATEGORY_ID));
create table category_language (CATEGORY_ID varchar(20) not null, LANGUAGE_CD varchar(5) not null, CATEGORY_NAME varchar(40), primary key (CATEGORY_ID, LANGUAGE_CD));
create table company (COMPANY_ID varchar(20) not null, TYPE_ID varchar(20), COMPANY_NAME varchar(60), LST_UPDATE timestamp, LST_UPDATED_BY varchar(20), PARENT_ID varchar(20), STATUS varchar(20), CREATE_DATE timestamp, CREATED_BY varchar(20), ALIAS varchar(40), DESCRIPTION varchar(40), DOMAIN_NAME varchar(40), LDAP_STR varchar(255), primary key (COMPANY_ID));
create table company_attachment_ref (COMPANY_ATTACH_REF_ID varchar(20) not null, COMPANY_ID varchar(20), NAME varchar(20), VALUE varchar(50), URL varchar(50), primary key (COMPANY_ATTACH_REF_ID));
create table company_attribute (COMPANY_ATTR_ID varchar(20) not null, METADATA_ID varchar(20), COMPANY_ID varchar(20), NAME varchar(20), VALUE varchar(255), primary key (COMPANY_ATTR_ID));
create table email_address (EMAIL_ID varchar(20) not null, NAME varchar(40), DESCRIPTION varchar(100), EMAIL_ADDRESS varchar(100), IS_DEFAULT integer, ACTIVE integer, PARENT_ID varchar(20) not null, PARENT_TYPE varchar(30) not null, primary key (EMAIL_ID));
create table exclude_word_list (WORD varchar(30) not null, LANGUAGE_CD varchar(5) not null, primary key (WORD, LANGUAGE_CD));
create table grp (GRP_ID varchar(20) not null, TYPE_ID varchar(20), GRP_NAME varchar(40), CREATE_DATE timestamp, CREATED_BY varchar(20), COMPANY_ID varchar(20), PARENT_GRP_ID varchar(20), INHERIT_FROM_PARENT integer, PROVISION_METHOD varchar(20), PROVISION_OBJ_NAME varchar(80), GROUP_CLASS varchar(40), GROUP_DESC varchar(80), STATUS varchar(20), LAST_UPDATE timestamp, LAST_UPDATED_BY varchar(20), POLICY_ID varchar(20), primary key (GRP_ID));
create table grp_attributes (ID varchar(20) not null, METADATA_ID varchar(20), GRP_ID varchar(20), NAME varchar(20), VALUE varchar(255), primary key (ID));
create table image (IMAGE_ID varchar(20) not null, IMAGE_FILE varchar(80), IMAGE_TYPE varchar(20), DESCRIPTION varchar(250), MIME_TYPE varchar(30), URL varchar(100), FILE_SIZE integer, IMAGE_BLOB varchar(255) for bit data, primary key (IMAGE_ID));
create table language (LANGUAGE_CD varchar(5) not null, LANGUAGE varchar(20), LOCALE integer, primary key (LANGUAGE_CD));
create table location (LOCATION_ID varchar(32) not null, NAME varchar(40), COUNTRY varchar(30), BLDG_NUM varchar(10), STREET_DIRECTION varchar(20), ADDRESS1 varchar(45), ADDRESS2 varchar(45), ADDRESS3 varchar(45), CITY varchar(30), STATE varchar(15), POSTAL_CD varchar(10), ORGANIZATION_ID varchar(20), ACTIVE integer, primary key (LOCATION_ID));
create table menu (MENU_ID varchar(20) not null, LANGUAGE_CD varchar(5) not null, MENU_GROUP varchar(20), MENU_NAME varchar(40), MENU_DESC varchar(40), URL varchar(100), ACTIVE integer, DISPLAY_ORDER integer, PUBLIC_URL integer, primary key (MENU_ID, LANGUAGE_CD));
create table metadata_element (METADATA_ID varchar(20) not null, TYPE_ID varchar(20), ATTRIBUTE_NAME varchar(50), DESCRIPTION varchar(40), MIN_LEN integer, MAX_LEN integer, TEXT_CASE varchar(10), DATA_TYPE varchar(20), MIN_VALUE bigint, MAX_VALUE bigint, DEFAULT_VALUE varchar(100), VALUE_LIST varchar(1000), LABEL varchar(100), MULTI_VALUE integer, AUDITABLE integer, REQUIRED integer, SELF_EDITABLE integer, SELF_VIEWABLE integer, UI_TYPE varchar(20), UI_OBJECT_SIZE varchar(40), VALUE_SRC varchar(1000), primary key (METADATA_ID));
create table metadata_type (TYPE_ID varchar(20) not null, DESCRIPTION varchar(40), ACTIVE integer, SYNC_MANAGED_SYS integer, primary key (TYPE_ID));
create table org_structure (ORG_STRUCTURE_ID varchar(20) not null, SUPERVISOR_ID varchar(20) not null, STAFF_ID varchar(20) not null, SUPERVISOR_TYPE varchar(20), IS_PRIMARY_SUPER integer, START_DATE timestamp, END_DATE timestamp, STATUS varchar(20), COMMENTS varchar(255), primary key (ORG_STRUCTURE_ID));
create table permissions (ROLE_ID varchar(20) not null, MENU_ID varchar(20) not null, primary key (ROLE_ID, MENU_ID));
create table phone (PHONE_ID varchar(20) not null, NAME varchar(40), AREA_CD varchar(10), COUNTRY_CD varchar(3), DESCRIPTION varchar(100), PHONE_NBR varchar(50), PHONE_EXT varchar(20), IS_DEFAULT integer, ACTIVE integer, PARENT_ID varchar(20) not null, PARENT_TYPE varchar(30) not null, primary key (PHONE_ID));
create table relation_set (RELATION_SET_ID varchar(20) not null, DESCRIPTION varchar(80), primary key (RELATION_SET_ID));
create table relation_source (RELATION_TYPE_ID varchar(20) not null, SOURCE_OBJ varchar(20) not null, SOURCE_ID varchar(20) not null, RELATION_SET_ID varchar(20), primary key (RELATION_TYPE_ID, SOURCE_OBJ, SOURCE_ID));
create table relation_type (RELATION_TYPE_ID varchar(20) not null, DESCRIPTION varchar(80) not null, primary key (RELATION_TYPE_ID));
create table relationship (RELATIONSHIP_ID varchar(20) not null, RELATION_SET_ID varchar(20), ITEM_OBJ varchar(20), ITEM_ID varchar(20), RANK integer, ACTIVE smallint, primary key (RELATIONSHIP_ID));
create table security_domain (DOMAIN_ID varchar(20) not null, NAME varchar(40), STATUS varchar(20), AUTH_SYS_ID varchar(20), LOGIN_MODULE varchar(100), primary key (DOMAIN_ID));
create table sequence_gen (ATTRIBUTE varchar(32) not null, NEXT_ID integer, primary key (ATTRIBUTE));
create table service (SERVICE_ID varchar(20) not null, SERVICE_NAME varchar(40), STATUS varchar(20), LOCATION_IP_ADDRESS varchar(80), COMPANY_OWNER_ID varchar(20), START_DATE timestamp, END_DATE timestamp, LICENSE_KEY varchar(255), SERVICE_TYPE varchar(20), PARENT_SERVICE_ID varchar(20), ROOT_RESOURCE_ID varchar(20), ACCESS_CONTROL_MODEL varchar(20), primary key (SERVICE_ID));
create table service_config (SERVICE_CONFIG_ID varchar(20) not null, SERVICE_ID varchar(20), NAME varchar(40), VALUE varchar(40), primary key (SERVICE_CONFIG_ID));
create table status (CODE_GROUP varchar(40) not null, STATUS_CD varchar(20) not null, LANGUAGE_CD varchar(2) not null, STATUS_TYPE varchar(20), DESCRIPTION varchar(80), WEIGHT integer, primary key (CODE_GROUP, STATUS_CD, LANGUAGE_CD));
create table user_attachment_ref (USER_ATTACH_REF_ID varchar(20) not null, USER_ID varchar(20), NAME varchar(20), VALUE varchar(50), URL varchar(50), primary key (USER_ATTACH_REF_ID));
create table user_attributes (ID varchar(20) not null, USER_ID varchar(20), METADATA_ID varchar(20), NAME varchar(20), VALUE varchar(255), ATTR_GROUP varchar(20), primary key (ID));
create table user_note (USER_NOTE_ID varchar(20) not null, USER_ID varchar(20), NOTE_TYPE varchar(20), DESCRIPTION varchar(1000), CREATE_DATE timestamp, CREATED_BY varchar(20), primary key (USER_NOTE_ID));
create table users (USER_ID varchar(20) not null, TYPE_ID varchar(20), FIRST_NAME varchar(40), LAST_NAME varchar(40), MIDDLE_INIT varchar(40), TITLE varchar(30), DEPT_CD varchar(50), DEPT varchar(50), DEPT_NAME varchar(100), MAIL_CODE varchar(50), DIVISION varchar(50), COST_CENTER varchar(20), STATUS varchar(20), BIRTHDATE timestamp, SEX char(1), CREATE_DATE timestamp, CREATED_BY varchar(20), LAST_UPDATE timestamp, LAST_UPDATED_BY varchar(20), PREFIX varchar(4), SUFFIX varchar(20), USER_TYPE_IND varchar(20), EMPLOYEE_ID varchar(20), EMPLOYEE_TYPE varchar(20), LOCATION_CD varchar(50), LOCATION_NAME varchar(100), COMPANY_ID varchar(20), COMPANY_OWNER_ID varchar(20), JOB_CODE varchar(50), MANAGER_ID varchar(20), START_DATE date, LAST_DATE date, MAIDEN_NAME varchar(40), NICKNAME varchar(40), PASSWORD_THEME varchar(20), primary key (USER_ID));
create table relation_category (CATEGORY_ID varchar(20) not null, RELATION_SET_ID varchar(20) not null, primary key (RELATION_SET_ID, CATEGORY_ID));
create table user_grp (USER_ID varchar(20) not null, GRP_ID varchar(20) not null, primary key (GRP_ID, USER_ID));
alter table category_type add constraint FK1432F9DBFE98176 foreign key (TYPE_ID) references metadata_type;
alter table category_type add constraint FK1432F9DBEDE9D9A7 foreign key (CATEGORY_ID) references category;
alter table category_language add constraint FK3466C579EDE9D9A7 foreign key (CATEGORY_ID) references category;
alter table category_language add constraint FK3466C579E8FB02AD foreign key (LANGUAGE_CD) references language;
alter table company add constraint FK38A73C7DFE98176 foreign key (TYPE_ID) references metadata_type;
alter table company_attachment_ref add constraint FK50DBFF79B82B0A4D foreign key (COMPANY_ID) references company;
alter table company_attribute add constraint FKC980295A6EB76FAB foreign key (METADATA_ID) references metadata_element;
alter table company_attribute add constraint FKC980295AB82B0A4D foreign key (COMPANY_ID) references company;
alter table exclude_word_list add constraint FK369C488EE8FB02AD foreign key (LANGUAGE_CD) references language;
alter table grp add constraint FK190E5FE98176 foreign key (TYPE_ID) references metadata_type;
alter table grp_attributes add constraint FKCD595CF16EB76FAB foreign key (METADATA_ID) references metadata_element;
alter table grp_attributes add constraint FKCD595CF188DEA2CD foreign key (GRP_ID) references grp;
alter table metadata_element add constraint FKAB85A1ECFE98176 foreign key (TYPE_ID) references metadata_type;
alter table org_structure add constraint FK6FCD89D8413229CD foreign key (SUPERVISOR_ID) references users;
alter table org_structure add constraint FK6FCD89D8FBA9E755 foreign key (STAFF_ID) references users;
alter table relation_source add constraint FKABFA77BEFD61B680 foreign key (RELATION_TYPE_ID) references relation_type;
alter table relation_source add constraint FKABFA77BE68783EB4 foreign key (RELATION_SET_ID) references relation_set;
alter table relationship add constraint FKF064763868783EB4 foreign key (RELATION_SET_ID) references relation_set;
alter table service_config add constraint FK73F5B40CC1803F4D foreign key (SERVICE_ID) references service;
alter table user_attachment_ref add constraint FKA8A0A6BA517928A foreign key (USER_ID) references users;
alter table user_attributes add constraint FK67C2564BA517928A foreign key (USER_ID) references users;
alter table user_attributes add constraint FK67C2564B6EB76FAB foreign key (METADATA_ID) references metadata_element;
alter table user_note add constraint FK143A23E6A517928A foreign key (USER_ID) references users;
alter table users add constraint FK6A68E08FE98176 foreign key (TYPE_ID) references metadata_type;
alter table relation_category add constraint FK32276FE1EDE9D9A7 foreign key (CATEGORY_ID) references category;
alter table relation_category add constraint FK32276FE168783EB4 foreign key (RELATION_SET_ID) references relation_set;
alter table user_grp add constraint FKF022CE71A517928A foreign key (USER_ID) references users;
alter table user_grp add constraint FKF022CE7188DEA2CD foreign key (GRP_ID) references grp;
