insert into ROLE(ROLE_ID, SERVICE_ID, ROLE_NAME) VALUES ('LSA', 'USR_SEC_DOMAIN', 'LSA');
insert into ROLE(ROLE_ID, SERVICE_ID, ROLE_NAME) VALUES ('MANAGER', 'USR_SEC_DOMAIN', 'MANAGER');
insert into ROLE(ROLE_ID, SERVICE_ID, ROLE_NAME) VALUES ('USER', 'USR_SEC_DOMAIN', 'USER');
insert into ROLE(ROLE_ID, SERVICE_ID, ROLE_NAME) VALUES ('CISO', 'USR_SEC_DOMAIN', 'CISO');
insert into ROLE(ROLE_ID, SERVICE_ID, ROLE_NAME) VALUES ('SECURITY', 'USR_SEC_DOMAIN', 'SECURITY');
insert into ROLE(ROLE_ID, SERVICE_ID, ROLE_NAME) VALUES ('HR', 'USR_SEC_DOMAIN', 'HR');

insert into GRP(GRP_ID, GRP_NAME) VALUES ('SUBMITTER', 'SUBMITTER');
insert into GRP(GRP_ID, GRP_NAME) VALUES ('REVIEWER', 'REVIEWER');
insert into GRP(GRP_ID, GRP_NAME) VALUES ('APPROVER', 'APPROVER');

COMMIT;

insert into USERS (user_id,first_name, last_name, STATUS, COMPANY_ID  ) values('3100','Neville','Bradbury','APPROVED','100');
insert into USER_GRP (grp_id, user_id) 	values('END_USER_GRP','3100');
insert into LOGIN(SERVICE_ID, LOGIN, MANAGED_SYS_ID, USER_ID, PASSWORD,RESET_PWD, IS_LOCKED, AUTH_FAIL_COUNT) VALUES('USR_SEC_DOMAIN','bradburyn@opensoftaustralia.com.au','USR_SEC_DOMAIN','3100','b83a81d1b3f5f209a70ec02c3d7f7fc5',0,0,0);
update LOGIN set reset_pwd = 0, is_locked = 0;

INSERT INTO AUTH_STATE(USER_ID, TOKEN, AUTH_STATE, AA, EXPIRATION) values('3100', NULL,0,'OPENIAM',0);
commit;
