package org.openiam.idm.srvc.menu.service;

import org.openiam.exception.data.DataException;
import org.openiam.idm.srvc.menu.dto.*;

import java.util.List;


/**
 * DAO interface for Menu
 * @author Suneet Shah
 *
 */
public interface NavigatorDAO {

	/**
	 * Return a Menu object for the id.
	 * @param id
	 */
	Menu findById(MenuId id)  throws DataException;
	/**
	 * Adds a new Menu object to the repository. If successful, the method
	 * return a Menu object that contains the objects ID. If an ID was not provided by the user,
	 * it will be autogenerated. .
	 * @param instance
	 */
	Menu add(Menu instance) throws DataException;
	/**
	 * Updates an existing Menu record
	 * @param instance
	 */
	void update(Menu instance) throws DataException;
	/**
	 * Remove a Menu record from the repository.
	 * @param instance
	 */
	void remove(Menu instance) throws DataException;
	
	int removeByMenuId(String menuId) throws DataException;
	
	List<Menu> findTopLevelMenus(String langCd) throws DataException;
	
	List<Menu> findSubMenus(String parentMenuId, String langCd) throws DataException;
	List<String> findSubMenuIDs(String parentMenuId, String langCd) throws DataException;
	List<Menu> findByMenuGroup(String menuGroup,String langCd) throws DataException;
	
	/**
	 * Returns a list of menus in the menu_group that a user is associated with in their role.
	 * @param menuGroupId
	 * @param userId
	 * @param languageCd
	 * @return
	 * @throws DataException
	 */
	List<Menu> findMenuByUser(String menuGroupId, String userId, String languageCd) throws DataException;

}
