package org.openiam.idm.srvc.service.dto;

// Generated Apr 19, 2007 12:21:40 AM by Hibernate Tools 3.2.0.beta8

/**
 * RequestApprover generated by hbm2java
 */
public class RequestApprover implements java.io.Serializable {

	// Fields    

	private String requestApproverId;

	private Service service;

	private String approverType;

	private String approverId;

	private String approvalLevel;

	// Constructors

	/** default constructor */
	public RequestApprover() {
	}

	/** minimal constructor */
	public RequestApprover(String requestApproverId) {
		this.requestApproverId = requestApproverId;
	}

	/** full constructor */
	public RequestApprover(String requestApproverId, Service service,
			String approverType, String approverId, String approvalLevel) {
		this.requestApproverId = requestApproverId;
		this.service = service;
		this.approverType = approverType;
		this.approverId = approverId;
		this.approvalLevel = approvalLevel;
	}

	// Property accessors
	public String getRequestApproverId() {
		return this.requestApproverId;
	}

	public void setRequestApproverId(String requestApproverId) {
		this.requestApproverId = requestApproverId;
	}

	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	public String getApproverType() {
		return this.approverType;
	}

	public void setApproverType(String approverType) {
		this.approverType = approverType;
	}

	public String getApproverId() {
		return this.approverId;
	}

	public void setApproverId(String approverId) {
		this.approverId = approverId;
	}

	public String getApprovalLevel() {
		return this.approvalLevel;
	}

	public void setApprovalLevel(String approvalLevel) {
		this.approvalLevel = approvalLevel;
	}

}
