package org.openiam.idm.srvc.role.dto;

// Generated Jul 18, 2009 8:49:09 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Object representing the User-Role relationship generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "userrole", propOrder = {
		 "userRoleId",
		 "serviceId",
		 "roleId",
		 "userId",
         "createDate",
         "status",
         "createdBy"
})
public class UserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3785768336629177182L;
	private String userRoleId;
	private String userId;
	private String serviceId;
	private String roleId;
	private String status;
	private Date createDate;
	private String createdBy;

	public UserRole() {
	}

	public UserRole( String userId, String serviceId, String roleId) {
		this.userId = userId;
		this.serviceId = serviceId;
		this.roleId = roleId;
		status = "ACTIVE";
		createDate = new Date(System.currentTimeMillis());
	}



	public String getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(String userRoleId) {
		this.userRoleId = userRoleId;
	}



	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
