package org.openiam.idm.srvc.synch.dto;

// Generated Sep 2, 2010 12:56:46 AM by Hibernate Tools 3.2.2.GA

/**
 * ActivityLogDetail generated by hbm2java
 */
public class ActivityLogDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8378687671721851836L;
	private String activityLogDetailId;
	private String activityLogId;
	private String msg;
	private String status;
	private String dataRow;

	public ActivityLogDetail() {
	}

	public ActivityLogDetail(String activityLogDetailId, String activityLogId) {
		this.activityLogDetailId = activityLogDetailId;
		this.activityLogId = activityLogId;
	}

	public ActivityLogDetail(String activityLogDetailId, String activityLogId,
			String msg, String status, String dataRow) {
		this.activityLogDetailId = activityLogDetailId;
		this.activityLogId = activityLogId;
		this.msg = msg;
		this.status = status;
		this.dataRow = dataRow;
	}

	public String getActivityLogDetailId() {
		return this.activityLogDetailId;
	}

	public void setActivityLogDetailId(String activityLogDetailId) {
		this.activityLogDetailId = activityLogDetailId;
	}

	public String getActivityLogId() {
		return this.activityLogId;
	}

	public void setActivityLogId(String activityLogId) {
		this.activityLogId = activityLogId;
	}

	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDataRow() {
		return this.dataRow;
	}

	public void setDataRow(String dataRow) {
		this.dataRow = dataRow;
	}

}
