package org.openiam.idm.srvc.synch.dto;


import java.util.Date;

/**
 * SynchActivityLog generated by hbm2java
 */
public class SynchActivityLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6485653279902427825L;
	private String activityLogId;
	private String logType;
	private String objectId;
	private Date logStartTime;
	private String status;

	public SynchActivityLog() {
	}

	public SynchActivityLog(String activityLogId, String logType,
			String objectId) {
		this.activityLogId = activityLogId;
		this.logType = logType;
		this.objectId = objectId;
	}

	public SynchActivityLog(String activityLogId, String logType,
			String objectId, Date logStartTime, String status) {
		this.activityLogId = activityLogId;
		this.logType = logType;
		this.objectId = objectId;
		this.logStartTime = logStartTime;
		this.status = status;
	}

	public String getActivityLogId() {
		return this.activityLogId;
	}

	public void setActivityLogId(String activityLogId) {
		this.activityLogId = activityLogId;
	}

	public String getLogType() {
		return this.logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	public String getObjectId() {
		return this.objectId;
	}

	public void setObjectId(String objectId) {
		this.objectId = objectId;
	}

	public Date getLogStartTime() {
		return this.logStartTime;
	}

	public void setLogStartTime(Date logStartTime) {
		this.logStartTime = logStartTime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
