
package org.openiam.idm.srvc.grp.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.1
 * Thu Aug 28 15:03:58 EDT 2008
 * Generated source version: 2.1.1
 * 
 */

public final class GroupDataService_GroupDataServicePort_Client {

    private static final QName SERVICE_NAME = new QName("urn:idm.openiam.org/srvc/grp/service", "GroupDataWebService");

    private GroupDataService_GroupDataServicePort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GroupDataWebService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GroupDataWebService ss = new GroupDataWebService(wsdlURL, SERVICE_NAME);
        GroupDataService port = ss.getGroupDataServicePort();  
        
        {
        System.out.println("Invoking removeUserFromGroup...");
        java.lang.String _removeUserFromGroup_arg0 = "";
        java.lang.String _removeUserFromGroup_arg1 = "";
        port.removeUserFromGroup(_removeUserFromGroup_arg0, _removeUserFromGroup_arg1);


        }
        {
        System.out.println("Invoking addAttribute...");
        org.openiam.idm.srvc.grp.dto.GroupAttribute _addAttribute_arg0 = null;
        port.addAttribute(_addAttribute_arg0);


        }
        {
        System.out.println("Invoking removeAllAttributes...");
        java.lang.String _removeAllAttributes_arg0 = "";
        port.removeAllAttributes(_removeAllAttributes_arg0);


        }
        {
        System.out.println("Invoking getAllAttributes...");
        java.lang.String _getAllAttributes_arg0 = "";
       // org.openiam.idm.srvc.grp.dto.GroupAttributeMap _getAllAttributes__return = port.getAllAttributes(_getAllAttributes_arg0);
        //System.out.println("getAllAttributes.result=" + _getAllAttributes__return);


        }
        {
        System.out.println("Invoking updateAttribute...");
        org.openiam.idm.srvc.grp.dto.GroupAttribute _updateAttribute_arg0 = null;
        port.updateAttribute(_updateAttribute_arg0);


        }
        {
        System.out.println("Invoking getParentGroup...");
        java.lang.String _getParentGroup_arg0 = "";
        boolean _getParentGroup_arg1 = false;
        org.openiam.idm.srvc.grp.dto.Group _getParentGroup__return = port.getParentGroup(_getParentGroup_arg0, _getParentGroup_arg1);
        System.out.println("getParentGroup.result=" + _getParentGroup__return);


        }
        {
        System.out.println("Invoking getGroupWithDependants...");
        java.lang.String _getGroupWithDependants_arg0 = "";
        org.openiam.idm.srvc.grp.dto.Group _getGroupWithDependants__return = port.getGroupWithDependants(_getGroupWithDependants_arg0);
        System.out.println("getGroupWithDependants.result=" + _getGroupWithDependants__return);


        }
        {
        System.out.println("Invoking removeGroup...");
        java.lang.String _removeGroup_arg0 = "";
        port.removeGroup(_removeGroup_arg0);


        }
        {
        System.out.println("Invoking getUserInGroups...");
        java.lang.String _getUserInGroups_arg0 = "";
        java.util.List<org.openiam.idm.srvc.grp.dto.Group> _getUserInGroups__return = port.getUserInGroups(_getUserInGroups_arg0);
        System.out.println("getUserInGroups.result=" + _getUserInGroups__return);


        }
        {
        System.out.println("Invoking getChildGroups...");
        java.lang.String _getChildGroups_arg0 = "";
        boolean _getChildGroups_arg1 = false;
        java.util.List<org.openiam.idm.srvc.grp.dto.Group> _getChildGroups__return = port.getChildGroups(_getChildGroups_arg0, _getChildGroups_arg1);
        System.out.println("getChildGroups.result=" + _getChildGroups__return);


        }
        {
        System.out.println("Invoking isUserInGroup...");
        java.lang.String _isUserInGroup_arg0 = "";
        java.lang.String _isUserInGroup_arg1 = "";
        boolean _isUserInGroup__return = port.isUserInGroup(_isUserInGroup_arg0, _isUserInGroup_arg1);
        System.out.println("isUserInGroup.result=" + _isUserInGroup__return);


        }
        {
        System.out.println("Invoking getUsersByGroup...");
        java.lang.String _getUsersByGroup_arg0 = "";
     //   org.openiam.idm.srvc.user.dto.UserSet _getUsersByGroup__return = port.getUsersByGroup(_getUsersByGroup_arg0);
     //   System.out.println("getUsersByGroup.result=" + _getUsersByGroup__return);


        }
        {
        System.out.println("Invoking removeAttribute...");
        org.openiam.idm.srvc.grp.dto.GroupAttribute _removeAttribute_arg0 = null;
        port.removeAttribute(_removeAttribute_arg0);


        }
        {
        System.out.println("Invoking getAllGroups...");
        java.util.List<org.openiam.idm.srvc.grp.dto.Group> _getAllGroups__return = port.getAllGroups();
        System.out.println("getAllGroups.result=" + _getAllGroups__return);


        }
        {
        System.out.println("Invoking getAttribute...");
        java.lang.String _getAttribute_arg0 = "";
        org.openiam.idm.srvc.grp.dto.GroupAttribute _getAttribute__return = port.getAttribute(_getAttribute_arg0);
        System.out.println("getAttribute.result=" + _getAttribute__return);


        }
        {
        System.out.println("Invoking addGroup...");
        org.openiam.idm.srvc.grp.dto.Group _addGroup_arg0 = null;
        port.addGroup(_addGroup_arg0);


        }
        {
        System.out.println("Invoking getGroup...");
        java.lang.String _getGroup_arg0 = "";
        org.openiam.idm.srvc.grp.dto.Group _getGroup__return = port.getGroup(_getGroup_arg0);
        System.out.println("getGroup.result=" + _getGroup__return);


        }
        {
        System.out.println("Invoking removeChildGroups...");
        java.lang.String _removeChildGroups_arg0 = "";
        int _removeChildGroups__return = port.removeChildGroups(_removeChildGroups_arg0);
        System.out.println("removeChildGroups.result=" + _removeChildGroups__return);


        }
        {
        System.out.println("Invoking getAllGroupsWithDependents...");
        boolean _getAllGroupsWithDependents_arg0 = false;
        java.util.List<org.openiam.idm.srvc.grp.dto.Group> _getAllGroupsWithDependents__return = port.getAllGroupsWithDependents(_getAllGroupsWithDependents_arg0);
        System.out.println("getAllGroupsWithDependents.result=" + _getAllGroupsWithDependents__return);


        }
        {
        System.out.println("Invoking updateGroup...");
        org.openiam.idm.srvc.grp.dto.Group _updateGroup_arg0 = null;
        port.updateGroup(_updateGroup_arg0);


        }
        {
        System.out.println("Invoking addUserToGroup...");
        java.lang.String _addUserToGroup_arg0 = "";
        java.lang.String _addUserToGroup_arg1 = "";
        port.addUserToGroup(_addUserToGroup_arg0, _addUserToGroup_arg1);


        }

        System.exit(0);
    }

}
