
/*
 * 
 */

package org.openiam.idm.srvc.grp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.1
 * Thu Aug 28 15:03:58 EDT 2008
 * Generated source version: 2.1.1
 * 
 */
 
/*
 * 
 */

@WebServiceClient(name = "GroupDataWebService", 
                  wsdlLocation = "file:src/main/webapp/WEB-INF/wsdl/GroupDataService.wsdl",
                  targetNamespace = "urn:idm.openiam.org/srvc/grp/service") 
public class GroupDataWebService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:idm.openiam.org/srvc/grp/service", "GroupDataWebService");
    public final static QName GroupDataServicePort = new QName("urn:idm.openiam.org/srvc/grp/service", "GroupDataServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/webapp/WEB-INF/wsdl/GroupDataService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/main/webapp/WEB-INF/wsdl/GroupDataService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public GroupDataWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GroupDataWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GroupDataWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns GroupDataService
     */
    @WebEndpoint(name = "GroupDataServicePort")
    public GroupDataService getGroupDataServicePort() {
        return super.getPort(GroupDataServicePort, GroupDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GroupDataService
     */
    @WebEndpoint(name = "GroupDataServicePort")
    public GroupDataService getGroupDataServicePort(WebServiceFeature... features) {
        return super.getPort(GroupDataServicePort, GroupDataService.class, features);
    }

}
