package org.openiam.idm.srvc.policy.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

// Generated Mar 7, 2009 11:47:12 AM by Hibernate Tools 3.2.2.GA

/**
 * PolicyMembership generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyMembership", propOrder = {
    "policyMemId",
    "policyId",
    "domainId",
    "resourceType",
    "resourceObjId"
})
public class PolicyMembership implements java.io.Serializable {

	private String policyMemId;
	private String policyId;
	private String domainId;
	private String resourceType;
	private String resourceObjId;

	public PolicyMembership() {
	}

	public PolicyMembership(String policyMemId) {
		this.policyMemId = policyMemId;
	}

	public PolicyMembership(String policyMemId, String policy,
			String serviceId, String resourceType, String resourceObjId) {
		this.policyMemId = policyMemId;
		this.policyId = policy;
		this.domainId = serviceId;
		this.resourceType = resourceType;
		this.resourceObjId = resourceObjId;
	}

	public String getPolicyMemId() {
		return this.policyMemId;
	}

	public void setPolicyMemId(String policyMemId) {
		this.policyMemId = policyMemId;
	}



	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public String getResourceObjId() {
		return this.resourceObjId;
	}

	public void setResourceObjId(String resourceObjId) {
		this.resourceObjId = resourceObjId;
	}

	public String getPolicyId() {
		return policyId;
	}

	public void setPolicyId(String policyId) {
		this.policyId = policyId;
	}

	public String getDomainId() {
		return domainId;
	}

	public void setDomainId(String domainId) {
		this.domainId = domainId;
	}

}
