package org.openiam.idm.srvc.policy.dto;

// Generated Mar 7, 2009 11:47:12 AM by Hibernate Tools 3.2.2.GA

/**
 * PolicyMembership generated by hbm2java
 */
public class PolicyMembership implements java.io.Serializable {

	private String policyMemId;
	private Policy policy;
	private String serviceId;
	private String resourceType;
	private String resourceObjId;

	public PolicyMembership() {
	}

	public PolicyMembership(String policyMemId) {
		this.policyMemId = policyMemId;
	}

	public PolicyMembership(String policyMemId, Policy policy,
			String serviceId, String resourceType, String resourceObjId) {
		this.policyMemId = policyMemId;
		this.policy = policy;
		this.serviceId = serviceId;
		this.resourceType = resourceType;
		this.resourceObjId = resourceObjId;
	}

	public String getPolicyMemId() {
		return this.policyMemId;
	}

	public void setPolicyMemId(String policyMemId) {
		this.policyMemId = policyMemId;
	}

	public Policy getPolicy() {
		return this.policy;
	}

	public void setPolicy(Policy policy) {
		this.policy = policy;
	}

	public String getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(String serviceId) {
		this.serviceId = serviceId;
	}

	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	public String getResourceObjId() {
		return this.resourceObjId;
	}

	public void setResourceObjId(String resourceObjId) {
		this.resourceObjId = resourceObjId;
	}

}
