package org.openiam.idm.srvc.recon.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

// Generated May 29, 2010 8:20:09 PM by Hibernate Tools 3.2.2.GA

/**
 * ReconiliationSituation generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReconciliationSituation", 
		propOrder = { "reconSituationId",
		"reconConfigId",
		"situation", 
		"situationResp",
		"respScript"})
public class ReconciliationSituation implements java.io.Serializable {

	private String reconSituationId;
	private String reconConfigId;
	private String situation;
	private String situationResp;
	private String preReconScript;
	private String postReconScript;


	
	public ReconciliationSituation() {
	}

	public ReconciliationSituation(String reconSituationId) {
		this.reconSituationId = reconSituationId;
	}

	public ReconciliationSituation(String reconSituationId,
			String reconConfigId, String situation, String situationResp) {
		this.reconSituationId = reconSituationId;
		this.reconConfigId = reconConfigId;
		this.situation = situation;
		this.situationResp = situationResp;
	}

	public String getReconSituationId() {
		return this.reconSituationId;
	}

	public void setReconSituationId(String reconSituationId) {
		this.reconSituationId = reconSituationId;
	}

	public String getReconConfigId() {
		return this.reconConfigId;
	}

	public void setReconConfigId(String reconConfigId) {
		this.reconConfigId = reconConfigId;
	}

	public String getSituation() {
		return this.situation;
	}

	public void setSituation(String situation) {
		this.situation = situation;
	}

	public String getSituationResp() {
		return this.situationResp;
	}

	public void setSituationResp(String situationResp) {
		this.situationResp = situationResp;
	}

	public String getPreReconScript() {
		return preReconScript;
	}

	public void setPreReconScript(String preReconScript) {
		this.preReconScript = preReconScript;
	}

	public String getPostReconScript() {
		return postReconScript;
	}

	public void setPostReconScript(String postReconScript) {
		this.postReconScript = postReconScript;
	}



}
