package org.openiam.idm.srvc.recon.dto;

// Generated May 29, 2010 8:20:09 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * ReconResultDetail generated by hbm2java
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReconciliationSituation", 
		propOrder = { "reconResultDetailId",
		"reconResultId",
		"objectKey", 
		"situation",
		"result"})
public class ReconResultDetail implements java.io.Serializable {

	private String reconResultDetailId;
	private String reconResultId;
	private String objectKey;
	private Date situation;
	private String result;

	public ReconResultDetail() {
	}

	public ReconResultDetail(String reconResultDetailId) {
		this.reconResultDetailId = reconResultDetailId;
	}

	public ReconResultDetail(String reconResultDetailId, String reconResultId,
			String objectKey, Date situation, String result) {
		this.reconResultDetailId = reconResultDetailId;
		this.reconResultId = reconResultId;
		this.objectKey = objectKey;
		this.situation = situation;
		this.result = result;
	}

	public String getReconResultDetailId() {
		return this.reconResultDetailId;
	}

	public void setReconResultDetailId(String reconResultDetailId) {
		this.reconResultDetailId = reconResultDetailId;
	}

	public String getReconResultId() {
		return this.reconResultId;
	}

	public void setReconResultId(String reconResultId) {
		this.reconResultId = reconResultId;
	}

	public String getObjectKey() {
		return this.objectKey;
	}

	public void setObjectKey(String objectKey) {
		this.objectKey = objectKey;
	}

	public Date getSituation() {
		return this.situation;
	}

	public void setSituation(Date situation) {
		this.situation = situation;
	}

	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

}
