

CREATE TABLE IDENTITY_QUEST_GRP (
       IDENTITY_QUEST_GRP_ID varchar(32) NOT NULL,
       NAME                 varchar(60) NULL,
       STATUS               varchar(20) NULL,
       COMPANY_OWNER_ID     varchar(32) NULL,
       CREATE_DATE          datetime NULL,
       CREATED_BY           varchar(20) NULL,
       LAST_UPDATE          datetime NULL,
       LAST_UPDATED_BY      varchar(20) NULL,
       PRIMARY KEY (IDENTITY_QUEST_GRP_ID)
) ENGINE=InnoDB;

CREATE TABLE IDENTITY_QUESTION (
       IDENTITY_QUESTION_ID 	varchar(32) NOT NULL,
       IDENTITY_QUEST_GRP_ID 	varchar(32) NULL,
       QUESTION_TEXT        	varchar(255) NULL,
       REQUIRED             	int NULL,
 		USER_ID			VARCHAR(32),	
       PRIMARY KEY (IDENTITY_QUESTION_ID),
       CONSTRAINT FK_IDENTITY_QUESTION_IDENTITY_QUEST_GRP
              FOREIGN KEY (IDENTITY_QUEST_GRP_ID) REFERENCES IDENTITY_QUEST_GRP(IDENTITY_QUEST_GRP_ID)
) ENGINE=InnoDB;
CREATE TABLE USER_IDENTITY_ANS (
       IDENTITY_ANS_ID      varchar(32) NOT NULL,
       IDENTITY_QUESTION_ID varchar(32) NULL,
	   QUESTION_TEXT		varchar(255) null,
       USER_ID              varchar(32) NULL,
       QUESTION_ANSWER      varchar(255) NULL,
       PRIMARY KEY (IDENTITY_ANS_ID), 
       CONSTRAINT FK_USER_IDENTITY_ANS_IDENTITY_QUESTION
       		FOREIGN KEY (IDENTITY_QUESTION_ID)  REFERENCES IDENTITY_QUESTION(IDENTITY_QUESTION_ID), 
       CONSTRAINT FK_USER_IDENTITY_ANS_USERS
       		FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
) ENGINE=InnoDB;

CREATE TABLE POLICY_DEF (
       POLICY_DEF_ID        varchar(32) NOT NULL,
       NAME                 varchar(60) NULL,
       DESCRIPTION          varchar(255) NULL,
       POLICY_TYPE          varchar(20) NULL,
       LOCATION_TYPE        varchar(20) NULL,
       POLICY_RULE          varchar(500) NULL,
       POLICY_HANDLER       varchar(255) NULL,
	POLICY_ADVISE_HANDLER	VARCHAR(255) NULL,
       PRIMARY KEY (POLICY_DEF_ID)
) ENGINE=InnoDB;

CREATE TABLE POLICY (
       POLICY_ID            varchar(32) NOT NULL,
       POLICY_DEF_ID        varchar(32) NULL,
       NAME                 varchar(60) NULL,
       DESCRIPTION          varchar(255) NULL,
       STATUS           	int NULL,
       CREATE_DATE          datetime NULL,
       CREATED_BY           varchar(20) NULL,
       LAST_UPDATE          datetime NULL,
       LAST_UPDATED_BY      varchar(20) NULL,
	   RULE					TEXT NULL,
       PRIMARY KEY (POLICY_ID), 
       CONSTRAINT FK_POLICY_POLICY_DEF
       	FOREIGN KEY (POLICY_DEF_ID) REFERENCES POLICY_DEF(POLICY_DEF_ID)
) ENGINE=InnoDB;


CREATE TABLE POLICY_MEMBERSHIP (
       POLICY_MEM_ID        varchar(32) NOT NULL,
       POLICY_ID            varchar(32) NULL,
       DOMAIN_ID           	varchar(20) NULL,
       RESOURCE_TYPE        varchar(20) NULL,
       RESOURCE_OBJ_ID      varchar(20) NULL,
       PRIMARY KEY (POLICY_MEM_ID), 
       CONSTRAINT FK_POLICY_MEMBERSHIP_POLICY
       		FOREIGN KEY (POLICY_ID) REFERENCES POLICY(POLICY_ID)
) ENGINE=InnoDB;

CREATE TABLE POLICY_DEF_PARAM (
       DEF_PARAM_ID         varchar(32) NOT NULL,
       POLICY_DEF_ID        varchar(32) NULL,
       NAME                 varchar(60) NULL,
       DESCRIPTION          varchar(255) NULL,
       OPERATION            varchar(20) NULL,
       VALUE1               varchar(255) NULL,
       VALUE2               varchar(255) NULL,
       REPEATS               int NULL,
	   PARAM_GROUP			varchar(20) NULL,
	POLICY_PARAM_HANDLER VARCHAR(255) NULL,
       PRIMARY KEY (DEF_PARAM_ID), 
       CONSTRAINT FK_POLICY_DEF_PARAM_POLICY_DEF
       		FOREIGN KEY (POLICY_DEF_ID) REFERENCES POLICY_DEF(POLICY_DEF_ID)
) ENGINE=InnoDB;

CREATE TABLE POLICY_ATTRIBUTE (
       POLICY_ATTR_ID       varchar(32) NOT NULL,
       DEF_PARAM_ID         varchar(32) NULL,
       POLICY_ID            varchar(32) NULL,
       NAME                 varchar(60) NULL,
       OPERATION            varchar(20) NULL,
       VALUE1               varchar(255) NULL,
       VALUE2               varchar(255) NULL,
       PRIMARY KEY (POLICY_ATTR_ID),
       CONSTRAINT FK_POLICY_ATTRIBUTE_POLICY_DEF_PARAM
       		FOREIGN KEY (DEF_PARAM_ID) REFERENCES POLICY_DEF_PARAM(DEF_PARAM_ID), 
       CONSTRAINT FK_POLICY_ATTRIBUTE_POLICY
       		FOREIGN KEY (POLICY_ID) REFERENCES POLICY(POLICY_ID)
) ENGINE=InnoDB;

CREATE TABLE AUTH_FLOW (
       AUTH_FLOW_ID         varchar(20) NOT NULL,
       CATEGORY_ID          varchar(20) NULL,
       NAME                 varchar(40) NULL,
       DESCRIPTION          varchar(255) NULL,
       CHALLENGE_METHOD     varchar(40) NULL,
       PRIMARY KEY (AUTH_FLOW_ID), 
	   CONSTRAINT FK_ATH_FLW_CAT
	       FOREIGN KEY (CATEGORY_ID)
                             REFERENCES CATEGORY (CATEGORY_ID)
) ENGINE=InnoDB;

CREATE TABLE AUTH_SEQUENCE (
       AUTH_SEQUENCE_ID     varchar(20) NOT NULL,
       AUTH_FLOW_ID         varchar(20) NULL,
       AUTH_METHOD          varchar(20) NULL,
       AUTH_SEQUENCE        int NULL,
       PRIMARY KEY (AUTH_SEQUENCE_ID), 
	   CONSTRAINT FK_ATH_SQ_ATH_FLW
       	FOREIGN KEY (AUTH_FLOW_ID)
                             REFERENCES AUTH_FLOW (AUTH_FLOW_ID)
) ENGINE=InnoDB;


CREATE TABLE AUTH_SEQUENCE_EVENT (
       SEQUENCE_EVENT_ID    varchar(20) NOT NULL,
       AUTH_SEQUENCE_ID     varchar(20) NULL,
       EVENT                varchar(20) NULL,
       INVOKE_URL           varchar(20) NULL,
       INVOKE_OBJ           varchar(20) NULL,
       PRIMARY KEY (SEQUENCE_EVENT_ID), 
	   CONSTRAINT FK_ATH_EV_ATH_SQ
       	FOREIGN KEY (AUTH_SEQUENCE_ID)
                             REFERENCES AUTH_SEQUENCE (AUTH_SEQUENCE_ID)
) ENGINE=InnoDB;

CREATE TABLE ENTITLEMENT (
       ENTITLEMENT_ID       varchar(20) NOT NULL,
       ENTITLEMENT_NAME     varchar(40) NULL,
       ENTITLEMENT_VALUE    varchar(80) NULL,
       DESCRIPTION          varchar(255) NULL,
       CREATE_DATE          datetime NULL,
       CREATED_BY           varchar(20) NULL,
       PRIMARY KEY (ENTITLEMENT_ID)
) ENGINE=InnoDB;

CREATE TABLE ROLE_ENTITLEMENT (
       ENTITLEMENT_ID       varchar(20) NOT NULL,
       ROLE_ID              varchar(20) NOT NULL,
       PRIMARY KEY (ENTITLEMENT_ID, ROLE_ID),
       CONSTRAINT RL_EN_RL
       	FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID),
	   CONSTRAINT RL_EN_EN
       	FOREIGN KEY (ENTITLEMENT_ID) REFERENCES ENTITLEMENT(ENTITLEMENT_ID)
) ENGINE=InnoDB;



CREATE TABLE RESOURCE_POLICY (
       RESOURCE_POLICY_ID   varchar(20) NOT NULL,
       ROLE_ID              varchar(20) NULL,
       RESOURCE_ID          varchar(20) NULL,
       POLICY_START         datetime NULL,
       POLICY_END           datetime NULL,
       APPLY_TO_CHILDREN    int NULL,
       PRIMARY KEY (RESOURCE_POLICY_ID), 
       CONSTRAINT RS_PL_RL_RLID 
       		FOREIGN KEY (ROLE_ID)
                             REFERENCES ROLE (ROLE_ID), 
       CONSTRAINT RS_PL_RS_RSID 
       		FOREIGN KEY (RESOURCE_ID)
                             REFERENCES RES(RESOURCE_ID)
) ENGINE=InnoDB;





CREATE TABLE AUDIT_POLICY (
       AUDIT_POLICY_ID      varchar(20) NOT NULL,
       CATEGORY_ID          varchar(20) NULL,
       LOG_FORMAT           varchar(1000) NULL,
       LOG_PARAM            varchar(1000) NULL,
       LOG_EVENTS           varchar(1000) NULL,
       PRIMARY KEY (AUDIT_POLICY_ID), 
       CONSTRAINT AUDPL_CATID
              FOREIGN KEY (CATEGORY_ID)
                             REFERENCES CATEGORY(CATEGORY_ID)
) ENGINE=InnoDB;


CREATE TABLE TIME_POLICY (
       TIME_POLICY_ID       char(18) NOT NULL,
       RESOURCE_POLICY_ID   varchar(20) NULL,
       CATEGORY_ID          varchar(20) NULL,
       ACTION               char(18) NULL,
       START_TIME           char(18) NULL,
       END_TIME             char(18) NULL,
       PRIMARY KEY (TIME_POLICY_ID), 
       CONSTRAINT TM_PL_RS_PL
       		FOREIGN KEY (RESOURCE_POLICY_ID)
                             REFERENCES RESOURCE_POLICY(RESOURCE_POLICY_ID), 
       CONSTRAINT TM_PL_CATID
       		FOREIGN KEY (CATEGORY_ID)
                             REFERENCES CATEGORY(CATEGORY_ID)
) ENGINE=InnoDB;

CREATE TABLE IP_POLICY (
       IP_POLICY_ID         varchar(20) NOT NULL,
       RESOURCE_POLICY_ID   varchar(20) NULL,
       CATEGORY_ID          varchar(20) NULL,
       ACTION               varchar(20) NULL,
       IP_START             varchar(20) NULL,
       IP_END               varchar(20) NULL,
       PRIMARY KEY (IP_POLICY_ID), 
       CONSTRAINT IP_PL_RS_PL
      		 FOREIGN KEY (RESOURCE_POLICY_ID)
                             REFERENCES RESOURCE_POLICY(RESOURCE_POLICY_ID),
       CONSTRAINT IP_PL_CATID 
       		 FOREIGN KEY (CATEGORY_ID)
                             REFERENCES CATEGORY(CATEGORY_ID)
) ENGINE=InnoDB;


CREATE TABLE POLICY_SCRIPT (
       POLICY_SCRIPT_ID     varchar(20) NOT NULL,
       RESOURCE_POLICY_ID   varchar(20) NULL,
       CATEGORY_ID          varchar(20) NULL,
       SEQUENCE_ID          int NULL,
       RULE                 varchar(2000) NULL,
       PRIMARY KEY (POLICY_SCRIPT_ID), 
       CONSTRAINT PL_SC_RS_PL
       		FOREIGN KEY (RESOURCE_POLICY_ID)
                             REFERENCES RESOURCE_POLICY(RESOURCE_POLICY_ID), 
       CONSTRAINT PL_SC_CATID 
       FOREIGN KEY (CATEGORY_ID)
                             REFERENCES CATEGORY(CATEGORY_ID)
) ENGINE=InnoDB;



CREATE TABLE PROVISION_CONNECTOR (
	CONNECTOR_ID 			varchar(32) NOT NULL,
	NAME		 			VARCHAR(40) NULL,
	METADATA_TYPE_ID		VARCHAR(20) NULL,
	STD_COMPLIANCE_LEVEL	VARCHAR(20) NULL,
	CLIENT_COMM_PROTOCOL	VARCHAR(20) NULL,
	SERVICE_URL				VARCHAR(100) NULL,
	SERVICE_NAMESPACE		VARCHAR(100) NULL,
	CLASS_NAME				VARCHAR(60) NULL,
	HOST					VARCHAR(60) NULL,
    PORT					VARCHAR(10) NULL,
	PRIMARY KEY(CONNECTOR_ID)
) ENGINE=InnoDB;



CREATE TABLE MANAGED_SYS (
       MANAGED_SYS_ID           VARCHAR(32) NOT NULL,
       NAME         						VARCHAR(40) NULL,
 	   DESCRIPTION							VARCHAR(80) NULL,
       STATUS								VARCHAR(20) NULL,
	   CONNECTOR_ID							VARCHAR(20) NOT NULL,
	   DOMAIN_ID							VARCHAR(20) NOT NULL,
	   HOST_URL								VARCHAR(80) NULL,
	   APPL_URL								VARCHAR(80) NULL,
	   PORT									INT NULL,
	   COMM_PROTOCOL						VARCHAR(20) NULL,
	   /* Need to accomodate fully qualified ldap names */
	   USER_ID								VARCHAR(150) NULL,
	   PSWD									VARCHAR(100) NULL,
	   START_DATE							DATE NULL,
	   END_DATE								DATE NULL,
	   RESOURCE_ID							VARCHAR(32) NULL,
       PRIMARY KEY (MANAGED_SYS_ID),
			 CONSTRAINT FK_MNG_SYS_PROV_CON
			 	FOREIGN KEY (CONNECTOR_ID) REFERENCES PROVISION_CONNECTOR(CONNECTOR_ID)
) ENGINE=InnoDB;

CREATE TABLE MNG_SYS_OBJECT_MATCH (
		OBJECT_SEARCH_ID	VARCHAR(32) NOT NULL,
		MANAGED_SYS_ID      VARCHAR(32) NOT NULL,
		/* USER, GROUP, ROLE, COMPUTER, RESOURCE, ETC */
		OBJECT_TYPE			VARCHAR(20) NULL DEFAULT 'USER',
		/* BASE_DN, SEARCH */ 
		MATCH_METHOD		VARCHAR(20) NULL DEFAULT 'BASE_DN',
		BASE_DN				VARCHAR(200) NULL,
		SEARCH_FILTER		VARCHAR(1000) NULL,
		KEY_FIELD			VARCHAR(40) NULL,
       PRIMARY KEY (OBJECT_SEARCH_ID),
			 CONSTRAINT FK_MNG_SYS_OBJ_MATC
			 	FOREIGN KEY (MANAGED_SYS_ID) REFERENCES MANAGED_SYS(MANAGED_SYS_ID)
) ENGINE=InnoDB;


CREATE TABLE MNG_SYS_GROUP(
    MNG_SYS_GROUP_ID    VARCHAR(32)    NOT NULL,
    MANAGED_SYS_ID      VARCHAR(32)    NOT NULL,
    PRIMARY KEY (MANAGED_SYS_ID, MNG_SYS_GROUP_ID), 
    CONSTRAINT Refmanaged_sys831 FOREIGN KEY (MANAGED_SYS_ID)
    REFERENCES MANAGED_SYS(MANAGED_SYS_ID)
) ENGINE=InnoDB;




CREATE TABLE PROV_REQUEST(
    REQUEST_ID        VARCHAR(32)     NOT NULL,
    REQUESTOR_ID      VARCHAR(20),
    REQUEST_DATE      DATETIME,
    STATUS            VARCHAR(20),
    STATUS_DATE       DATETIME,
    REQUEST_REASON    VARCHAR(500),
	REQUEST_TYPE VARCHAR(20),
    PRIMARY KEY (REQUEST_ID)
) ENGINE=InnoDB;

CREATE TABLE REQ_APPROVER(
    REQ_APPROVER_ID     VARCHAR(32)    NOT NULL,
    APPROVER_ID         VARCHAR(32)	   NULL,
    APPROVER_TYPE		VARCHAR(20)    NULL,   /* MANAGER, APP_APPROVER, FORM_APPROVER */
    APPROVER_LEVEL      VARCHAR(20)	   NULL,
    REQUEST_ID          VARCHAR(32)    NULL,
    ACTION_DATE         DATETIME       NULL,
    STATUS              VARCHAR(20)    NULL,  /* PENDING, COMPLETE */
    ACTION              VARCHAR(20)    NULL,  /* APPROVE, REJECT, DELEGATE */
    COMMENT             VARCHAR(500)   NULL,
    MNG_SYS_GROUP_ID    VARCHAR(32)    NULL,
    MANAGED_SYS_ID      VARCHAR(32)    NULL,
    PRIMARY KEY (REQ_APPROVER_ID)
) ENGINE=InnoDB;


CREATE TABLE DATA_SOURCE(
    DATA_SOURCE_ID    VARCHAR(32)    NOT NULL,
    CLASS_NAME        VARCHAR(20),
    DRIVER_URL        VARCHAR(20),
    USER_NAME         VARCHAR(40),
    USER_PASSWORD     VARCHAR(80),
    PRIMARY KEY (DATA_SOURCE_ID)
) ENGINE=InnoDB;

CREATE TABLE PROV_FORM(
    FORM_ID                VARCHAR(32)     NOT NULL,
    NAME                   VARCHAR(50),
    DESCRIPTION            VARCHAR(100),
    MANAGED_SYS_ID         VARCHAR(32),
    MNG_SYS_GROUP_ID       VARCHAR(32),
    AUTO_GEN               INTEGER,
    CUSTOM_FORM_URL        VARCHAR(20),
    CUSTOM_FORM_HANDLER    VARCHAR(80),
    PROCESS_NAME           VARCHAR(20),
    SEND_MSG               INTEGER,
    DISPLAY_COLS           INT,
    PRIMARY KEY (FORM_ID)
) ENGINE=InnoDB;

CREATE TABLE PROV_QUESTION_BANK(
    PROV_QUEST_ID           VARCHAR(32)     NOT NULL,
    QUESTION_TEXT           VARCHAR(500),
    ANS_UI_OBJECT           VARCHAR(20),
    ANS_UI_OBJECT_SIZE      VARCHAR(20),
    ANS_LIST                VARCHAR(500),
    LIST_QUERY              VARCHAR(500),
    LIST_WEBSERVICE_URL     VARCHAR(80),
    WEBSERIVCE_OPERATION    VARCHAR(20),
    DATA_SOURCE_ID          VARCHAR(32)     NOT NULL,
    PRIMARY KEY (PROV_QUEST_ID), 
    CONSTRAINT RefDATA_SOURCE851 FOREIGN KEY (DATA_SOURCE_ID)
    REFERENCES DATA_SOURCE(DATA_SOURCE_ID)
) ENGINE=InnoDB;

CREATE TABLE FORM_QUESTION(
    FORM_ID          VARCHAR(32)    NOT NULL,
    PROV_QUEST_ID    VARCHAR(20)    NOT NULL,
    DISPLAY_ORDER    INT,
    PRIMARY KEY (FORM_ID, PROV_QUEST_ID), 
    CONSTRAINT RefPROV_FORM911 FOREIGN KEY (FORM_ID)
    REFERENCES PROV_FORM(FORM_ID),
    CONSTRAINT RefPROV_QUESTION_BANK921 FOREIGN KEY (PROV_QUEST_ID)
    REFERENCES PROV_QUESTION_BANK(PROV_QUEST_ID)
) ENGINE=InnoDB;


CREATE TABLE MNG_SYS_LIST(
    MANAGED_SYS_ID    VARCHAR(32)    NOT NULL,
    REQUEST_ID        VARCHAR(32)    NOT NULL,
    PRIMARY KEY (MANAGED_SYS_ID, REQUEST_ID), 
    CONSTRAINT Refmanaged_sys941 FOREIGN KEY (MANAGED_SYS_ID)
    REFERENCES MANAGED_SYS(MANAGED_SYS_ID),
    CONSTRAINT RefPROV_REQUEST951 FOREIGN KEY (REQUEST_ID)
    REFERENCES PROV_REQUEST(REQUEST_ID)
) ENGINE=InnoDB;

CREATE TABLE REQUEST_ATTACHMENT(
    REQUEST_ATTACHMENT_ID    VARCHAR(32)    NOT NULL,
    NAME                     VARCHAR(20),
    ATTACHMENT               VARCHAR(20),
    USER_ID                  VARCHAR(32),
    ATTACHMENT_DATE          VARCHAR(20),
    REQUEST_ID               VARCHAR(32)    NOT NULL,
    PRIMARY KEY (REQUEST_ATTACHMENT_ID), 
    CONSTRAINT RefPROV_REQUEST1001 FOREIGN KEY (REQUEST_ID)
    REFERENCES PROV_REQUEST(REQUEST_ID)
) ENGINE=InnoDB;

CREATE TABLE REQUEST_ATTRIBUTE(
    REQUEST_ATTR_ID    VARCHAR(32)    NOT NULL,
    NAME               VARCHAR(20),
    VALUE              VARCHAR(20),
    METADATA_ID        VARCHAR(20),
    ATTR_GROUP         VARCHAR(20),
    REQUEST_ID         VARCHAR(32)    NOT NULL,
    PRIMARY KEY (REQUEST_ATTR_ID), 
    CONSTRAINT RefPROV_REQUEST1011 FOREIGN KEY (REQUEST_ID)
    REFERENCES PROV_REQUEST(REQUEST_ID)
) ENGINE=InnoDB;

CREATE TABLE REQUEST_USER(
    REQ_USER_ID    VARCHAR(32)    NOT NULL,
    USER_ID             VARCHAR(32),
    FIRST_NAME          VARCHAR(20),
    LAST_NAME           VARCHAR(20),
    MIDDLE_INIT         VARCHAR(20),
    DEPT_CD             VARCHAR(20),
    DIVISION            VARCHAR(20),
    LOCATION_CD         VARCHAR(20),
    AFFILIATION         VARCHAR(20),
    REQUEST_ID          VARCHAR(32)    NOT NULL,
    PRIMARY KEY (REQ_USER_ID), 
    CONSTRAINT RefPROV_REQUEST931 FOREIGN KEY (REQUEST_ID)
    REFERENCES PROV_REQUEST(REQUEST_ID)
) ENGINE=InnoDB;


CREATE TABLE SYS_ATTRIBUTE_MAP (
       ATTRIBUTE_MAP_ID          		VARCHAR(32) NOT NULL,
			 MANAGED_SYS_ID           	VARCHAR(32) NOT NULL,
			 /* User, Group, OTHER 										*/
			 OBJECT_GROUP				VARCHAR(20) DEFAULT 'USER',
			 /* CN, DN, UID, ETC   */
			 TARGET_ATTRIBUTE_NAME		VARCHAR(40) NULL,
			 /* IS AUTHORITATIVE SRC. 0-FALSE, 1-TRUE */
			 AUTHORITATIVE_SRC			INT DEFAULT 0,
			 /* POLICY, IN-LINE 											*/
			 RULE_SOURCE				VARCHAR(20) NULL,
			 RULE						TEXT,
			 STATUS						VARCHAR(20) DEFAULT 'ACTIVE',
			 START_DATE					DATE,
			 END_DATE					DATE,
       PRIMARY KEY (ATTRIBUTE_MAP_ID),
			 CONSTRAINT FK_SYS_ATR_MNG_SYS
			 	FOREIGN KEY (MANAGED_SYS_ID) REFERENCES MANAGED_SYS(MANAGED_SYS_ID)
) ENGINE=InnoDB;


/* views */

CREATE VIEW USER_ROLE_VW AS 
SELECT ug.USER_ID, gr.ROLE_ID
FROM USER_GRP ug LEFT JOIN GRP_ROLE gr on (ug.GRP_ID = gr.GRP_ID)
		 WHERE gr.ROLE_ID is not null
 UNION
SELECT ur.USER_ID,  ur.ROLE_ID
FROM USER_ROLE ur 
	WHERE ur.ROLE_ID is not null
	ORDER BY USER_ID;	
	
CREATE VIEW USER_EMAIL_VW AS 
	SELECT *
	FROM EMAIL_ADDRESS
	WHERE NAME = 'EMAIL1' AND PARENT_TYPE='USER';

CREATE VIEW USER_PHONE_VW AS 
SELECT *
FROM PHONE
WHERE NAME = 'DESK PHONE' AND PARENT_TYPE='USER';



CREATE TABLE SECURITY_ACCESS_LOG (
      ACCESS_LOG_ID        varchar(32) NOT NULL,
      USER_ID              varchar(20) NOT NULL,
      LOG_TIME             datetime NOT NULL,
      SERVICE_ID           varchar(20) NULL,
      LOGIN_ID             varchar(30) NULL,
      ACTION               varchar(40) NULL,
      HOST_IP              varchar(60) NULL,
      REQ_URL              varchar(60) NULL,
      REQUEST_METHOD       VARCHAR(30) NULL,
      DESCRIPTION		   VARCHAR(500) NULL,
      PRIMARY KEY (ACCESS_LOG_ID)
) ENGINE=InnoDB;


ALTER TABLE STATUS
	ADD COLUMN  COMPANY_OWNER_ID		VARCHAR(20) NOT NULL,
  ADD COLUMN  SERVICE_ID           varchar(20) NOT NULL;

ALTER TABLE SERVICE
	ADD COLUMN  PARAM1		VARCHAR(20) NULL,
	ADD COLUMN  PARAM2		VARCHAR(20) NULL,
	ADD COLUMN  PARAM3		VARCHAR(20) NULL,
	ADD COLUMN  PARAM4		VARCHAR(20) NULL,
	ADD COLUMN  PARAM5		VARCHAR(20) NULL;





ALTER TABLE POLICY
 DROP FOREIGN KEY FK_POLICY_POLICY_DEF,
 ADD ENABLEMENT INT DEFAULT '1' AFTER RULE;



ALTER TABLE LOGIN
ADD INDEX login_user_indx (USER_ID);

ALTER TABLE USERS
  ADD INDEX USER_EMPLOYEE_INDX (EMPLOYEE_ID);
commit;