
/*
 * 
 */

package org.openiam.idm.srvc.user.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.1
 * Fri Aug 22 09:18:46 EDT 2008
 * Generated source version: 2.1.1
 * 
 */
 
/*
 * 
 */

@WebServiceClient(name = "UserDataWebService", 
                  wsdlLocation = "file:src/main/webapp/WEB-INF/wsdl/UserDataService.wsdl",
                  targetNamespace = "urn:idm.openiam.org/srvc/user/service") 
public class UserDataWebService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:idm.openiam.org/srvc/user/service", "UserDataWebService");
    public final static QName UserDataServicePort = new QName("urn:idm.openiam.org/srvc/user/service", "UserDataServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/webapp/WEB-INF/wsdl/UserDataService.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/main/webapp/WEB-INF/wsdl/UserDataService.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public UserDataWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserDataWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserDataWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns UserDataService
     */
    @WebEndpoint(name = "UserDataServicePort")
    public UserDataService getUserDataServicePort() {
        return super.getPort(UserDataServicePort, UserDataService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserDataService
     */
    @WebEndpoint(name = "UserDataServicePort")
    public UserDataService getUserDataServicePort(WebServiceFeature... features) {
        return super.getPort(UserDataServicePort, UserDataService.class, features);
    }

}
