delete from USER_ATTRIBUTES;
DELETE FROM AUTH_STATE;
DELETE FROM LOGIN_ATTRIBUTE;
DELETE FROM LOGIN;
DELETE FROM USER_ROLE;
DELETE FROM USER_GRP;
DELETE FROM USER_IDENTITY_ANS;
DELETE FROM USER_NOTE;
DELETE FROM EMAIL_ADDRESS;
DELETE FROM PHONE;
DELETE FROM ADDRESS;
DELETE FROM ORG_STRUCTURE;
DELETE FROM USERS;
commit;

insert into USERS (user_id,first_name, last_name, STATUS, COMPANY_ID ) values('3000','sys','','ACTIVE','100');
insert into USERS (user_id,first_name, last_name, STATUS, COMPANY_ID ) values('3001','sys2','','ACTIVE','100');

insert into LOGIN(SERVICE_ID, LOGIN, MANAGED_SYS_ID, USER_ID, PASSWORD,RESET_PWD, IS_LOCKED, AUTH_FAIL_COUNT) VALUES('IDM','sysadmin','0','3000','b83a81d1b3f5f209a70ec02c3d7f7fc5',0,0,0);
insert into LOGIN(SERVICE_ID, LOGIN, MANAGED_SYS_ID, USER_ID, PASSWORD,RESET_PWD, IS_LOCKED, AUTH_FAIL_COUNT) VALUES('USR_SEC_DOMAIN','sysadmin','0','3000','b83a81d1b3f5f209a70ec02c3d7f7fc5',0,0,0);

insert into USER_GRP (USER_GRP_ID, grp_id, user_id) 	values('1000','SUPER_SEC_ADMIN_GRP','3000');
insert into USER_GRP (USER_GRP_ID,grp_id, user_id) 	values('1001','SUPER_SEC_ADMIN_GRP','3001');

commit;


