package org.openiam.idm.srvc.mngsys.dto;

import java.util.Iterator;

// Generated Dec 24, 2009 9:53:19 PM by Hibernate Tools 3.2.2.GA

/**
 * ResApprover generated by hbm2java

 */
public class ApproverAssociation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6664731921635130368L;
	private String approverAssocId;
	private String requestType;
	private String action;
	private String associationObjId;
	private String approverUserId;
	private String approverName;
	private String associationType;
	private Integer approverLevel;
	protected Boolean selected = new Boolean(false);

 
	
	public ApproverAssociation() {
	}



	public String getApproverAssocId() {
		return approverAssocId;
	}



	public void setApproverAssocId(String approverAssocId) {
		this.approverAssocId = approverAssocId;
	}



	public String getRequestType() {
		return requestType;
	}



	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}



	public String getAction() {
		return action;
	}



	public void setAction(String action) {
		this.action = action;
	}



	public String getAssociationObjId() {
		return associationObjId;
	}



	public void setAssociationObjId(String associationObjId) {
		this.associationObjId = associationObjId;
	}



	public String getApproverUserId() {
		return approverUserId;
	}



	public void setApproverUserId(String approverUserId) {
		this.approverUserId = approverUserId;
	}



	public String getAssociationType() {
		return associationType;
	}



	public void setAssociationType(String associationType) {
		this.associationType = associationType;
	}



	public Integer getApproverLevel() {
		return approverLevel;
	}



	public void setApproverLevel(Integer approverLevel) {
		this.approverLevel = approverLevel;
	}



	public Boolean getSelected() {
		return selected;
	}



	public void setSelected(Boolean selected) {
		this.selected = selected;
	}



	public String getApproverName() {
		return approverName;
	}



	public void setApproverName(String approverName) {
		this.approverName = approverName;
	}



}
