package org.openiam.idm.srvc.mngsys.dto;

import java.util.Iterator;

// Generated Dec 24, 2009 9:53:19 PM by Hibernate Tools 3.2.2.GA

/**
 * ResApprover generated by hbm2java

 */
public class ResourceApprover implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6664731921635130368L;
	private String resApproverId;
	private String managedSysId;
	private String taskAction;
	private String approverId;
	private String approverType;
	private Integer approverLevel;
	private String msgId;

	public ResourceApprover() {
	}

	public ResourceApprover(String resApproverId) {
		this.resApproverId = resApproverId;
	}

	public ResourceApprover(String resApproverId, String managedSys,
			String taskAction, String approverId, String approverType,
			Integer approverLevel, String msgId) {
		this.resApproverId = resApproverId;
		this.managedSysId = managedSys;
		this.taskAction = taskAction;
		this.approverId = approverId;
		this.approverType = approverType;
		this.approverLevel = approverLevel;
		this.msgId = msgId;
	}

	public String getResApproverId() {
		return this.resApproverId;
	}

	public void setResApproverId(String resApproverId) {
		this.resApproverId = resApproverId;
	}


	public String getTaskAction() {
		return this.taskAction;
	}

	public void setTaskAction(String taskAction) {
		this.taskAction = taskAction;
	}

	public String getApproverId() {
		return this.approverId;
	}

	public void setApproverId(String approverId) {
		this.approverId = approverId;
	}

	public String getApproverType() {
		return this.approverType;
	}

	public void setApproverType(String approverType) {
		this.approverType = approverType;
	}

	public Integer getApproverLevel() {
		return this.approverLevel;
	}

	public void setApproverLevel(Integer approverLevel) {
		this.approverLevel = approverLevel;
	}

	public String getMsgId() {
		return this.msgId;
	}

	public void setMsgId(String msgId) {
		this.msgId = msgId;
	}

	public String getManagedSysId() {
		return managedSysId;
	}

	public void setManagedSysId(String managedSysId) {
		this.managedSysId = managedSysId;
	}



}
