package org.openiam.idm.srvc.service.dto;

// Generated Apr 19, 2007 12:21:40 AM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * RequestForm generated by hbm2java
 */
public class RequestForm implements java.io.Serializable {

	// Fields    

	private RequestFormId id;

	private Service service;

	private Integer isDefault;

	private Date createDate;

	private String createdBy;

	private String formTemplateUrl;

	// Constructors

	/** default constructor */
	public RequestForm() {
	}

	/** minimal constructor */
	public RequestForm(RequestFormId id, Service service) {
		this.id = id;
		this.service = service;
	}

	/** full constructor */
	public RequestForm(RequestFormId id, Service service, Integer isDefault,
			Date createDate, String createdBy, String formTemplateUrl) {
		this.id = id;
		this.service = service;
		this.isDefault = isDefault;
		this.createDate = createDate;
		this.createdBy = createdBy;
		this.formTemplateUrl = formTemplateUrl;
	}

	// Property accessors
	public RequestFormId getId() {
		return this.id;
	}

	public void setId(RequestFormId id) {
		this.id = id;
	}

	public Service getService() {
		return this.service;
	}

	public void setService(Service service) {
		this.service = service;
	}

	public Integer getIsDefault() {
		return this.isDefault;
	}

	public void setIsDefault(Integer isDefault) {
		this.isDefault = isDefault;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getFormTemplateUrl() {
		return this.formTemplateUrl;
	}

	public void setFormTemplateUrl(String formTemplateUrl) {
		this.formTemplateUrl = formTemplateUrl;
	}

}
