package org.openiam.idm.srvc.mngsys.dto;

// Generated Nov 3, 2008 12:14:43 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * SysApprover generated by hbm2java
 */
public class SysApprover implements java.io.Serializable {

	private String sysApproverId;
	private ManagedSys managedSys;
	private String approverType;
	private String approverId;
	private Integer approvalLevel;
	private String status;
	private Date startDate;
	private Date endDate;

	public SysApprover() {
	}

	public SysApprover(String sysApproverId, ManagedSys managedSys) {
		this.sysApproverId = sysApproverId;
		this.managedSys = managedSys;
	}

	public SysApprover(String sysApproverId, ManagedSys managedSys,
			String approverType, String approverId, Integer approvalLevel,
			String status, Date startDate, Date endDate) {
		this.sysApproverId = sysApproverId;
		this.managedSys = managedSys;
		this.approverType = approverType;
		this.approverId = approverId;
		this.approvalLevel = approvalLevel;
		this.status = status;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public String getSysApproverId() {
		return this.sysApproverId;
	}

	public void setSysApproverId(String sysApproverId) {
		this.sysApproverId = sysApproverId;
	}

	public ManagedSys getManagedSys() {
		return this.managedSys;
	}

	public void setManagedSys(ManagedSys managedSys) {
		this.managedSys = managedSys;
	}

	public String getApproverType() {
		return this.approverType;
	}

	public void setApproverType(String approverType) {
		this.approverType = approverType;
	}

	public String getApproverId() {
		return this.approverId;
	}

	public void setApproverId(String approverId) {
		this.approverId = approverId;
	}

	public Integer getApprovalLevel() {
		return this.approvalLevel;
	}

	public void setApprovalLevel(Integer approvalLevel) {
		this.approvalLevel = approvalLevel;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
