package org.openiam.idm.srvc.mngsys.dto;

// Generated Nov 3, 2008 12:14:43 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * SysAttributeMap generated by hbm2java
 */
public class SysAttributeMapping implements java.io.Serializable {

	private String attributeMapId;
	private ManagedSys managedSys;
	private String objectGroup;
	private String targetAttributeName;
	private Integer authoritativeSrc;
	private String ruleSource;
	private String rule;
	private String status;
	private Date startDate;
	private Date endDate;

	public SysAttributeMapping() {
	}

	public SysAttributeMapping(String attributeMapId, ManagedSys managedSys) {
		this.attributeMapId = attributeMapId;
		this.managedSys = managedSys;
	}

	public SysAttributeMapping(String attributeMapId, ManagedSys managedSys,
			String objectGroup, String targetAttributeName,
			Integer authoritativeSrc, String ruleSource, String rule,
			String status, Date startDate, Date endDate) {
		this.attributeMapId = attributeMapId;
		this.managedSys = managedSys;
		this.objectGroup = objectGroup;
		this.targetAttributeName = targetAttributeName;
		this.authoritativeSrc = authoritativeSrc;
		this.ruleSource = ruleSource;
		this.rule = rule;
		this.status = status;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public String getAttributeMapId() {
		return this.attributeMapId;
	}

	public void setAttributeMapId(String attributeMapId) {
		this.attributeMapId = attributeMapId;
	}

	public ManagedSys getManagedSys() {
		return this.managedSys;
	}

	public void setManagedSys(ManagedSys managedSys) {
		this.managedSys = managedSys;
	}

	public String getObjectGroup() {
		return this.objectGroup;
	}

	public void setObjectGroup(String objectGroup) {
		this.objectGroup = objectGroup;
	}

	public String getTargetAttributeName() {
		return this.targetAttributeName;
	}

	public void setTargetAttributeName(String targetAttributeName) {
		this.targetAttributeName = targetAttributeName;
	}

	public Integer getAuthoritativeSrc() {
		return this.authoritativeSrc;
	}

	public void setAuthoritativeSrc(Integer authoritativeSrc) {
		this.authoritativeSrc = authoritativeSrc;
	}

	public String getRuleSource() {
		return this.ruleSource;
	}

	public void setRuleSource(String ruleSource) {
		this.ruleSource = ruleSource;
	}

	public String getRule() {
		return this.rule;
	}

	public void setRule(String rule) {
		this.rule = rule;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
